- name: install snapshot requirements
  ansible.builtin.pip:
    name:
      - tqdm 
      - requests
    executable: pip3

- name: download latest snapshot
  become: true
  become_user: solana
  shell: python3 snapshot-finder.py --snapshot_path /mnt/solana-snapshots --max_latency 1000 

