- name: mnt folder
  file:
    path: "{{ base_path }}"
    state: directory
    owner: solana
    group: solana
    mode: "0777"
  become: true
  become_user: root

- name: solana snapshots
  file:
    path: "{{ base_path }}/solana-snapshots"
    state: directory
    owner: solana
    group: solana
  become: true
  become_user: root

- name: solana ledger
  file:
    path: "{{ base_path }}/solana-ledger"
    state: directory
    owner: solana
    group: solana
  become: true
  become_user: root

- name: solana accounts
  file:
    path: "{{ base_path }}/solana-accounts"
    state: directory
    owner: solana
    group: solana
  become: true
  become_user: root

- name: solana logs
  become: true
  become_user: root
  file:
    path: "{{ base_path }}/logs"
    state: directory
    owner: solana
    group: solana
